fix: allow to create vertx proxy options from property resolver
gravitee-io/gravitee-common pull request #72
Opened 2022-05-13 08:17 UTC by a-cordier

Environment not being allways accessed from spring application context
we need a method that accepepts directly the property resolver as an
argument

**Additional context**

2022-05-17 11:39 UTC, brasseld requested changes
I could be wrong @a-cordier but it sounds like this is duplicating what we already have in https://github.com/gravitee-io/gravitee-node/blob/master/gravitee-node-api/src/main/java/io/gravitee/node/api/configuration/Configuration.java#L21 

WDYT ?

2022-05-17 11:41 UTC, brasseld commented
That is already use by some modules like the HTTP connector: https://github.com/gravitee-io/gravitee-connector-http/blob/master/src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java#L75

2022-05-17 15:06 UTC, a-cordier commented
@brasseld thanks! didn't thought about checking which implementations we had already in place for `Configuration`

2022-05-18 11:55 UTC, a-cordier commented on src/main/java/io/gravitee/common/util/VertxProxyOptionsUtils.java
> +    public static ProxyOptions buildProxyOptions(Configuration configuration) {
@brasseld In order to keep gateway [endpoint resolvers](https://github.com/gravitee-io/gravitee-api-management/pull/1784/files) able to build proxy options once and for all, maybe we should keep this method and propose the other as an alternative ?

2022-05-19 08:28 UTC, merged

2022-05-19 08:33 UTC, graviteeio commented
:tada: This PR is included in version 1.26.1 :tada:

The release is available on:
- `1.26.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-common/releases/tag/1.26.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: